package com.hallap.reserveerimissysteem.controller;

import com.hallap.reserveerimissysteem.dto.*;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.List;
import java.util.Map;

// This Controller has been written by me except where noted otherwise. - Mark

@RestController
@RequestMapping("/api/v1")
@RequiredArgsConstructor
public class ReservationApiController {

    @GetMapping("/layout")
    public LayoutResponse getLayout() {
        // TODO: I'll need to write a check for table insertion into the db later.
        // 1) I'll need the table to be within venue bounds (center + half width/height within venue dimensions)
        // 2) AND each table needs clearance in relation to neighbors. Neighbor-wise 2 half-widths/heights + ~0.6m clearance
        // maybe overthinking? But I think it would be sensible, otherwise we are inviting strange UI / overlap issues etc.
        return new LayoutResponse(
                "layout1", 20.0, 30.0,
                List.of(
                        new LayoutResponse.ZoneSummary(Zone.INDOOR, "Indoor", "Cozy Indoor area"),
                        new LayoutResponse.ZoneSummary(Zone.TERRACE, "Terrace", "Heated Terrace with a View")
                ),
                List.of(
                        new LayoutResponse.TableGeometry("T1", "Table 1", 4, Zone.INDOOR, new LayoutResponse.Point(4.0, 4.0), 1.2, 0.8, 0.0),
                        new LayoutResponse.TableGeometry("T2", "Table 2", 2, Zone.INDOOR, new LayoutResponse.Point(6.0, 6.0), 0.8, 0.8, 0.0),
                        new LayoutResponse.TableGeometry("T3", "Table 3", 3, Zone.INDOOR, new LayoutResponse.Point(8.0, 7.8), 1.0, 0.8, 0.0),
                        new LayoutResponse.TableGeometry("T4", "Table 4", 6, Zone.TERRACE, new LayoutResponse.Point(11.2, 5.8), 1.8, 1.0, 0.0)
                )
        );
    }

    @PostMapping("/availability")
    public AvailabilityResponse checkAvailability(
            @RequestBody AvailabilityRequest availabilityRequest
    ) {
        Map<String, AvailabilityStatus> statusMap = Map.of(
                "T1", AvailabilityStatus.AVAILABLE,
                "T2", AvailabilityStatus.UNAVAILABLE,
                "T3", AvailabilityStatus.AVAILABLE,
                "T4", AvailabilityStatus.RESERVED
        );
        return new AvailabilityResponse(statusMap, Instant.now());
    }

    @PostMapping("/recommendations")
    public RecommendationsResponse getRecommendations(
            @RequestBody RecommendationsRequest recommendationsRequest
    ) {
        List<Recommendation> recommendations = List.of(new Recommendation(
                "T1",
                100,
                List.of("See on Sulle hea laud, sest...")));
        return new RecommendationsResponse("T1", recommendations);
    }

    @PostMapping("/reservations")
    public ReservationResponse makeReservation(
            @RequestBody ReservationRequest reservationRequest
    ) {
        // this sample response has been generated by AI
        return new ReservationResponse(
                "rsv_demo_1",
                reservationRequest.tableId(),
                reservationRequest.date(),
                reservationRequest.time(),
                reservationRequest.partySize(),
                ReservationStatus.CONFIRMED,
                Instant.now(),
                "Broneering kinnitatud"
        );
    }

    @GetMapping("/reservations/{id}")
    public ReservationResponse getReservation(@PathVariable String id) {
        // this sample response has been generated by AI
        return new ReservationResponse(
                id,
                "T1",
                "2026-03-21",
                "19:30",
                4,
                ReservationStatus.CONFIRMED,
                Instant.now(),
                "Broneering kinnitatud"
        );
    }
}
