// Theme demo is generated by AI

import {
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Container,
  Divider,
  Paper,
  Stack,
  Typography,
} from '@mui/material'
import { useTheme } from '@mui/material/styles'

function ThemeDemo() {
  const theme = useTheme()

  const paletteSwatches = [
    { label: 'Primary', color: theme.palette.primary.main },
    { label: 'Secondary', color: theme.palette.secondary.main },
    { label: 'Warning', color: theme.palette.warning.main },
    { label: 'Success', color: theme.palette.success.main },
    { label: 'Background', color: theme.palette.background.default },
  ]

  return (
    <Box
      sx={{
        minHeight: '100vh',
        py: { xs: 4, md: 8 },
        background:
          'radial-gradient(circle at 5% 0%, rgba(180, 58, 47, 0.14), transparent 35%), radial-gradient(circle at 95% 10%, rgba(95, 64, 56, 0.12), transparent 30%)',
      }}
    >
      <Container maxWidth="lg">
        <Stack spacing={4}>
          <Paper sx={{ p: { xs: 3, md: 4 } }}>
            <Stack spacing={2}>
              <Chip label="Teema eelvaade" color="secondary" sx={{ width: 'fit-content' }} />
              <Typography variant="h2" component="h1">
                Theme Demo
              </Typography>
              <Typography variant="body1" color="text.secondary">
                This route is kept for visual testing while the main Home page focuses on booking flow.
              </Typography>
              <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}>
                <Button variant="contained" color="primary">
                  Primary action
                </Button>
                <Button variant="outlined" color="secondary">
                  Secondary action
                </Button>
              </Stack>
            </Stack>
          </Paper>

          <Box
            sx={{
              display: 'grid',
              gridTemplateColumns: {
                xs: '1fr',
                sm: 'repeat(2, minmax(0, 1fr))',
                md: 'repeat(5, minmax(0, 1fr))',
              },
              gap: 2,
            }}
          >
            {paletteSwatches.map((swatch) => (
              <Card key={swatch.label} variant="outlined">
                <CardContent>
                  <Box
                    sx={{
                      height: 72,
                      borderRadius: 2,
                      mb: 1.5,
                      backgroundColor: swatch.color,
                      border: '1px solid rgba(0,0,0,0.08)',
                    }}
                  />
                  <Typography variant="subtitle2">{swatch.label}</Typography>
                  <Typography variant="caption" color="text.secondary">
                    {swatch.color.toUpperCase()}
                  </Typography>
                </CardContent>
              </Card>
            ))}
          </Box>

          <Paper sx={{ p: { xs: 3, md: 4 } }}>
            <Typography variant="h3" gutterBottom>
              Demo text
            </Typography>
            <Divider sx={{ mb: 2 }} />
            <Stack spacing={1.2}>
              <Typography color="text.secondary">Excellent, the tables have turned</Typography>
              <Typography color="text.secondary">Ich werde in Restaurant gehen</Typography>
              <Typography color="text.secondary">Je suis une gourmande</Typography>
            </Stack>
          </Paper>
        </Stack>
      </Container>
    </Box>
  )
}

export default ThemeDemo
